### ISSUE TITLE
Al ver el detalle de una noticia no se ve la fecha de la misma

### ISSUE THREAD

**Issue by emiarias** [Charlycarral/rollingNews#1]
Agregar la fecha de la noticia en la pagina de detalle

![image](https://user-images.githubusercontent.com/18445151/155358913-1aa30bd9-5ad8-4d53-bcac-d9815e7b9116.png)

**Comment by RamiroIsaJ** [comment]
Solucionado. Se ha publicado en cada noticia, la fecha en la que ha sido agredada.
