### ISSUE TITLE
Quitar los mensaje en consola

### ISSUE THREAD

**Issue by emiarias** [Charlycarral/rollingNews#2]
Limpiar todos los mensaje de la consola como respuestas del backend, usuario y pregunta secreta del administrador etc. 

![image](https://user-images.githubusercontent.com/18445151/155359248-19259c9e-48c8-4ea6-a651-f51e80f314e1.png)

**Comment by RamiroIsaJ** [comment]
Solucionado. Se han eliminado los mensajes en la consola.

**Comment by emiarias** [comment]
Quedan mensajes en consola por ej, al seleccionar una seccion desde el footer se ven las fechas de las noticias exihibidas.
