### ISSUE TITLE
Al Agregar o editar  una categoria se puede poner cualquier cantidad de caracteres en el nombre

### ISSUE THREAD

**Issue by emiarias** [Charlycarral/rollingNews#4]
Establecer un limite maximo de caracteres en el nombre de la categoria, si no se controla este dato se rompe el diseño en la pagina de categorias.

![image](https://user-images.githubusercontent.com/18445151/155360422-b445212a-c62f-4365-9c97-100b428938fb.png)

**Comment by RamiroIsaJ** [comment]
Solucionado. Se ha definido el maxlength para cada caso: Agregar y editar categoría. Además se han definido también un máximo de caracteres para los campos relacionados con las noticias.
