### ISSUE TITLE
No se puede editar la fecha de una noticia

### ISSUE THREAD

**Issue by emiarias** [Charlycarral/rollingNews#6]
El campo de la fecha deberia ser de tipo date, al cargar una fecha diferente no podemos modificar la misma no se ve un error en la pagina del usuario pero si en consola.

![image](https://user-images.githubusercontent.com/18445151/157123439-be8713b2-5b38-45f7-9c84-da7fd402ddd4.png)
![image](https://user-images.githubusercontent.com/18445151/157123483-5365279f-8256-4f3e-a9ef-d4e9aa530ee6.png)

**Comment by RamiroIsaJ** [comment]
Solucionado. Se ha definido tipo date la fecha en el script para editar noticia.
