### ISSUE TITLE
Error de fechas al mostrar una noticia

### ISSUE THREAD

**Issue by emiarias** [Charlycarral/rollingNews#7]
Al crear una nueva noticia seleccionamos una fecha, en el momento de mostrar esa noticia se visualiza con un dia de menos. Ademas mostrar todas las fechas con el mismo formato, si la web es en español usar el formato DD/MM/YYYY.

![image](https://user-images.githubusercontent.com/18445151/157125302-202d5fb1-01b3-4351-afd9-64abf7f464bf.png)

![image](https://user-images.githubusercontent.com/18445151/157125043-022631f3-d5d9-49ca-9c4d-81a6eed52e6f.png)

**Comment by RamiroIsaJ** [comment]
Solucionado. El formato de la fecha para nuestra web quedó {yyyy - mm - dd}. El día actual es la máxima fecha para subir una noticia.
